### ISSUE TITLE
Consolidate here

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-utils#1]
See https://github.com/cerc-io/ipld-eth-statedb/issues/4

To reduce the number of repos we need to independently maintain (esp inre to rebasing the stack)

1. https://github.com/cerc-io/ipld-eth-statedb
2. <s>https://github.com/cerc-io/go-ethereum/tree/v1.11.4-statediff-v4/trie/concurrent_iterator</s>
3. https://github.com/cerc-io/ipfs-ethdb
4. The yet to be written trie.Trie that passes CIDs down into ipfs-ethdb instead of keccak256 hashes
5. Shared test fixtures
6. Common `sql.Database` abstraction

**Comment by i-norden** [comment]
See https://github.com/cerc-io/go-ethereum/issues/204 for num 6

**Comment by roysc** [comment]
We should decide how to structure the packages in here. We have one `pkg` which is a good convention in most cases (esp. if we have `cmd` for CLI stuff), but makes less sense to me in a repo of distinct, though related, utility packages.

It's also worth choosing clear names, since everything _is_ interrelated. Right now I have `bycid` as the WIP name of the parent package for the ipfs-ethdb related stuff, since state is indexed by CID, and I want to differentiate it from the ipld-eth-statedb components indexed by leaf path (so was thinking `bypath` or `flat`). I don't love any of these, though.

Also, is there any advantage to using separate Go modules here? Seems doubtful, but worth asking. Everything is versioned together anyway, and even if it's broken up, dependents would indirectly pull in most of the same stuff since there's so much overlap.

And, I'm guessing we want to bump the version tags straight to `v5` so they match the existing infrastructure?

**Comment by i-norden** [comment]
I agree on `pkg`. Doesn't make sense here since we won't have a `cmd` dir. Would be better to have the various packages at the top level. 

For the ipld-eth-statedb packages I think we should have a top dir/pkg `ipld-eth-statedb` and I think this should have sub directories/pkgs for `trie` and `direct`. I think the trie traversal vs looking up directly in `state_cids`/`storage_cids` is the bigger differentiation between the two implementations but maybe `trie_by_cid` is better as it also signifies why we cant use the stock `StateDB` with ipfs-ethdb.

I also can't see much advantage to using separate go modules here, like you said for the most part everything will be static except for when all the pkgs need to be updated, simulatenously, due to a geth version bump or an ipld-eth-db schema change.

Yeah let's go straight to v5. Although for packages like the concurrent iterator I am beginning to think it makes sense to leave it in our geth fork, it isn't tied to any specific version of ipld-eth-db/doesn't have anything (direclty) to do with ipld. Neither do the trie_builder_utils I added here, should probably stick those in geth instead.

**Comment by i-norden** [comment]
You know, now that we aren't going to move the concurrent iterator here.. and since ipfs-ethdb doesn't seem to be needed in v5. I am question whether or not we still have enough to justify consolidating here. What do you think @roysc ?

**Comment by roysc** [comment]
That's a good point. We can probably shelve this until we identify a bigger use case for it, e.g. refactoring test support. I think have smaller tool and testing packages in a lightweight repo would still be handy.

**Comment by i-norden** [comment]
That sounds good to me @roysc, if you don't mind please port your PR over to the ipld-eth-statedb repo. I'll port the trie utils into geth during the next rebase or something.
